version: '2'

tasks:
  clean:
    desc: cleanup local working directory
    silent: true
    cmds:
      - rm -rf .pioenvs
  upload:
    desc: upload to target device locally
    silent: true
    cmds:
      - pio run -t upload
  test:
    desc: run all tests after each other
    cmds:
      - task: test-native
      - task: test-embedded
  test-native:
    desc: run test locally
    cmds:
    - pio test -e native  -v
  test-embedded:
    desc: run test on target environment
    cmds:
    - pio test -e nanoatmega328  -v
  test-remote:
    desc: run all tests after each other - embedded tests on remote device
    cmds:
      - task: test-native
      - task: test-remote-embedded
  test-remote-embedded:
    desc: run test on target environment
    cmds:
    - pio remote test -e nanoatmega328  -v
  update-pio:
    desc: update platformio locally
    silent: true
    cmds:
      - pio -f upgrade
      - pio -f update
