#ifndef HAY_DISPENSER_ABSTRACTDIGITALINPUT_H
#define HAY_DISPENSER_ABSTRACTDIGITALINPUT_H

class AbstractDigitalInput
{
public:
  virtual bool isOn() = 0;
};

#endif // HAY_DISPENSER_ABSTRACTDIGITALINPUT_Hx
